sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: sINhYo1O7zCZgV5SPlcI1Rhv1fLIHxkPaOmOzgbxpjv1ehxULCaqD+BfoCDqK+XynS7f6xJfFainH2Fi2YbD1owzhfRMyXmbdWWnCvXdBvWOh2FVN6NPpCveVadQlcLkRvnIVj1bfH8peFETK3LJ6Aehh8yRRt/4lHlB3j5nwIux7ajLJQ5aGDq2kGUo560kvC9bN7ghi86qtFaneH2YSQ/I+6hvSA7tbKetm0bD1picPJM3Qjd2ob6vrobQpRXmDER86bmjsqZcnA9BZsTtEfGu/Ibu0auMS8UmQauJk2fNzW0voHpFu8ce0EMKo/QFMnCX1Y7zY2m1rSveoVTB3cfwEkpdaRdVc8CpezFIFRQZUCAseidDQufiG2rOITB/nBz0fqM+Oax2+499jXsq+Rpz1ZEnPFstOuchs9Jaziqdfv7Z13v1KG2BM8vz91JFHyit7pNZ9+ecTPFgtXQvYANdDGi9hLfdoaK7gQaaWdpEIdAFNj09pW5Gmoea44qdbtF4D1sPkLTwZd9xBu77aoS3+myt4eqSS73du0u7aWUufH/xj4oG/W3m5CQTAJSAW0ee3Kbc9EamMpvJ5JulUJ6TbV4DzvCjpqS62hjtpd/23vNr4zaiGF0o5CTXIiQsTmv/MsPjqK+5y786IT4AXUkcCZcbcd3v1TiDOQgbxU4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Miss-Sarah-Jack-of-Spanish-Town-Jamaica_3699
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy